# Generated by Django 5.0.6 on 2024-07-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(choices=[('py', 'py'), ('cpp', 'cpp')], max_length=100),
        ),
    ]
