# Generated by Django 5.0.6 on 2024-07-05 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_codesubmission_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('statement', models.TextField()),
                ('constraints', models.TextField()),
                ('inputs', models.TextField()),
                ('outputs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DummyTestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.CharField(max_length=255)),
                ('output_data', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.problem')),
            ],
        ),
    ]
