# Generated by Django 5.0.6 on 2024-07-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_problem_dummytestcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummytestcases',
            name='input_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dummytestcases',
            name='output_data',
            field=models.TextField(),
        ),
    ]
