# Generated by Django 5.0.6 on 2024-07-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_dummytestcases_input_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='passed_testcases',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(choices=[('passed', 'passed'), ('failed', 'failed'), ('compile-error', 'compile-error')], default='passed', max_length=100),
        ),
    ]
