# Generated by Django 5.0.6 on 2024-07-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_codesubmission_passed_testcases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='status',
            field=models.CharField(choices=[('passed', 'passed'), ('failed', 'failed'), ('compile-error', 'compile-error'), ('runtime-error', 'runtime-error')], default='passed', max_length=100),
        ),
    ]
