# Generated by Django 5.0.6 on 2024-07-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_problem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.problem'),
        ),
    ]
