# Generated by Django 5.0.6 on 2024-07-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_testcases_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='topics',
            field=models.CharField(choices=[('arrays', 'arrays'), ('strings', 'strings'), ('stack', 'stack'), ('queue', 'queue'), ('priority queue', 'priority queue'), ('DP', 'DP'), ('graphs', 'graphs'), ('maths', 'maths')], default='maths', max_length=100),
        ),
    ]
