# Generated by Django 5.0.6 on 2024-07-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_problem_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
